[package]
name = "advent-of-code-2015"
version = "0.1.0"
authors = ["sebas <jingfee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.9.1"
itertools = "0.9.0"
regex = "1"
pcre2 = "0.1"